name: Ubuntu rvv VLEN=256 (gcc 14)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: |
        sudo apt-get update -q -y
        sudo apt-get install -y cmake make g++-14-riscv64-linux-gnu qemu-user-static
    - name: Build
      run: |
        CC=riscv64-linux-gnu-gcc-14 CXX=riscv64-linux-gnu-g++-14 CFLAGS=-march=rv64gcv CXXFLAGS="${CFLAGS}" \
        cmake --toolchain=cmake/toolchains-ci/riscv64-linux-gnu.cmake -DSIMDJSON_DEVELOPER_MODE=ON -B build
        cmake --build build/ -j$(nproc) --config Release
    - name: Test VLEN=256
      run: |
        QEMU_LD_PREFIX="/usr/riscv64-linux-gnu" \
        QEMU_CPU="rv64,v=on,zvbb=on,vlen=256,rvv_ta_all_1s=on,rvv_ma_all_1s=on" \
        ctest --timeout 1800 --output-on-failure --test-dir build -j $(nproc)
    - name: Build VLS
      run: |
        CC=riscv64-linux-gnu-gcc-14 CXX=riscv64-linux-gnu-g++-14 CFLAGS="-march=rv64gcv_zvl256b -mrvv-vector-bits=zvl" CXXFLAGS="${CFLAGS}" \
        cmake --toolchain=cmake/toolchains-ci/riscv64-linux-gnu.cmake -DSIMDJSON_DEVELOPER_MODE=ON -B build-vls
        cmake --build build-vls/ -j$(nproc) --config Release
    - name: Test VLEN=256 VLS
      run: |
        QEMU_LD_PREFIX="/usr/riscv64-linux-gnu" \
        QEMU_CPU="rv64,v=on,zvbb=on,vlen=256,rvv_ta_all_1s=on,rvv_ma_all_1s=on" \
        ctest --timeout 1800 --output-on-failure --test-dir build-vls -j $(nproc)
